server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Xiao-huanhuan123/SpringcloudConfig.git #GitHub上面的git仓库名字
          search-paths:
            - SpringcloudConfig #搜索目录
      label: main #读取分支

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka