server:
  port: 80

spring:
  application:
    name: consul-order-service
  cloud:
    consul:
      host: 192.168.1.149
      port: 8500
      discovery:
        service-name: ${spring.application.name}