server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.149:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    #初始化链接数
    initialSize: 5
    #最小的空闲连接数
    minIdle: 5
    #最大活动连接数
    maxActive: 20
    #从池中取连接的最大等待时间，单位ms
    maxWait: 60000
    #每XXms运行一次空闲连接回收器
    timeBetweenEvictionRunsMillis: 60000
    #池中的连接空闲XX毫秒后被回收
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.whlearn.springcloud.entities

eureka:
  client:
    fetch-registry: true #表示将自己注册进EurekaServer
    fetchRegistry: true #从EurekaServer抓取已有的注册信息，单节点不影响，集群必须设置为true才能ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群
  instance:
    instance-id: payment8002
    prefer-ip-address: true