server:
  port: 80


eureka:
  client:
    fetch-registry: true #表示将自己注册进EurekaServer
    fetchRegistry: true #从EurekaServer抓取已有的注册信息，单节点不影响，集群必须设置为true才能ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

##设置feign客户端超时时间（openFeign默认支持ribbon）
ribbon:
  ConnectTimeout: 10000 #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 10000 #指的是建立连接后从服务器读取到可用资源所用的时间

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
